### ISSUE TITLE
Something wrong =(

### ISSUE THREAD

**Issue by AlterEgo00001** [mnick-yt/Chat-Bot-using-gpt-3.5-turbo#1]
![изображение](https://user-images.githubusercontent.com/81518780/226192170-1bc91c42-0509-4400-a0f3-7380e82f2d3a.png)

**Comment by rcsmit** [comment]
If you look in your terminal you see _AttributeError: module 'openai' has no attribute 'ChatCompletion'_ I googled it and found the solution (ChatGPT didnt know btw ;)) : You have to upgrade openai

You can do this with 
`pip install --upgrade openai`

**Comment by AlterEgo00001** [comment]
![изображение](https://user-images.githubusercontent.com/81518780/226280695-49d912ec-5fc0-43f1-acdb-95e9ab8870ca.png)

**Comment by tondeaf** [comment]
Nothing happens.

**Comment by mnick-yt** [comment]
issue solved. updated index.html file.
